### ISSUE TITLE
Compatible with new kuksa.val version 0.1.10

### ISSUE THREAD

**Issue by wenwenchenbosch** [GENIVI/iot-event-analytics#105]
It would be nice to let iotea compatible with new kuksa.val version [0.1.10](https://github.com/eclipse/kuksa.val/releases/tag/0.1.10) or at least [0.1.8](https://github.com/eclipse/kuksa.val/releases/tag/0.1.8)

https://github.com/GENIVI/iot-event-analytics/blob/dd3b2bed465f087da6f5e100faf7dbdd6e3497f4/src/sdk/javascript/examples/integrations/kuksa.val/.env#L4

Because kuksa-val:98f961b is still a very old commit and it is not possible to download the image anymore from jenkins. It will be better to be compatible with a tagged kuksa-val version.

API changes of `kuksa.val` is documented in the [release page](https://github.com/eclipse/kuksa.val/releases). If any support for `kuksa.val` needed, just contact me.

**Comment by SebastianSchildt** [comment]
Probably this should reopen #71 , if the problem was not fixed there.

(It says there fixed in #99 , but maybe that is wrong)

**Comment by wenwenchenbosch** [comment]
@SebastianSchildt You are right. It is also an option. At least, I should be tracked.

**Comment by llakie** [comment]
We actually updated it in the given pull request. We could reupdate it to image to the most recent `amd64/kuksa-val:be15568`.

**Comment by wenwenchenbosch** [comment]
@llakie  thanks very much for the quick answer and solution. I will recommand to update kuksa_val image to [amd/kuksa-val:0.1.10](https://ci.eclipse.org/kuksa/job/kuksa.val/view/tags/job/0.1.10/). There should be no difference between 0.1.10 and be15568 regarding to `kuksa.val` server.
The only problem is we recycle the jenkins build for master. In the future, it is quite difficult for user to download a certain version of docker image. Release version can always be downloaded from jenkins and auch from [release page](https://github.com/eclipse/kuksa.val/releases/tag/0.1.10).

**Comment by llakie** [comment]
I updated to version `amd64/kuksa-val:4a9b4a0` and fixed some issues with the example and the adapter.
Could you check the timestamp Kuksa.Val creates? It seems to me, that there are numbers appended to the given Zulu timestamp (which is in Long-Form `YYYY-MM-DDTHH:mm:ss.SSSZ`). I receive `YYYY-MM-DDTHH:mm:ss.SSSZXXX` whereas XXX is some numeric value and which leads to problems when parsing that value. We just cut after the `Z` now to make it compatible.
Please note:
The error could also be on our side, since we expected Milliseconds as an Integer. If we just got seconds, we appended the Milliseconds to the end. So if the error is not on your side, we have this fixed as well ;)

**Comment by wenwenchenbosch** [comment]
Thanks @llakie, I will check it

**Comment by llakie** [comment]
Discussed with @SebastianSchildt and clarified the ISO formatting stuff covered in VISS Spec v2.

**Comment by wenwenchenbosch** [comment]
Hi @llakie why did you close this issue? would you like to close the https://github.com/eclipse/kuksa.val/issues/210 instead of? Or can you link this issue to some PR you did for the compatibility with kuksa val 0.1.10?

**Comment by wenwenchenbosch** [comment]
found the fix in pr https://github.com/GENIVI/iot-event-analytics/pull/110
