### ISSUE TITLE
Visual Studio Code Plugin (VSIX) error logs at postinstall

### ISSUE THREAD

**Issue by BDUG** [GENIVI/iot-event-analytics#38]
In some installations the error "Cannot find module '/build/postinstalls.js' appears at internal/main/run_main_module.js:17:11.

**Comment by llakie** [comment]
Please provide further information about the installations you are referring to. I assume it's potentially the installation of the SDK where the postinstall script tries to download the artifacts. This should actually not happen, since it'll always return a 0 exit code (See package.json in IoT Event Analytics project directory).
For further investigation on this issue, I need more information of how to reproduce this error. Could you please give me a hint on that?

**Comment by llakie** [comment]
Fixed, since we removed the postinstall section completly and replaced it with a manual installation or creation of the SDKs.
