### ISSUE TITLE
Time series talent rules result in unexpected triggering of "onEvent" method

### ISSUE THREAD

**Issue by BDUG** [GENIVI/iot-event-analytics#41]
With timeseries conditions e.g. as given in the basic example with pattern 3256, one matching condition causes an "onEvent"-trigger for each event in the series. IMHO this is unexpected. I would expect one "onEvent" trigger for the whole matched time series.

**Comment by llakie** [comment]
I think I got your point. The constraint is actually working as expected, but since the other rule evaluated to true earlier and both of them are packed together in an OR rule, the whole rule evaluates to true, no matter if the PatternConstraint matches or not.
We might change this example in the future to separate the behavior.

**Comment by BDUG** [comment]
THX
