### ISSUE TITLE
Is it possible to provide documentation on the software architecture of the platform

### ISSUE THREAD

**Issue by BDUG** [GENIVI/iot-event-analytics#42]
Would it be possible to provide at least a component as well as deployment UML diagram in the documentation? It is quite hard to understand the relationship between the GENIVI project "Vehicle Edge" and "IoT Event Analytics".

**Comment by llakie** [comment]
There are some deployment diagrams available using PlantUML since PR #80. This only deals with IoT Event Analytics and its components. The connection to Vehicle-Edge is not explained here, since Vehicle Edge builds on top of IoT Event Analytics and therefore has to be contained rather in the Vehicle Edge project than in the IoT Event Analytics.
Please reopen your issue in the Vehicle-Edge repository.
